<?php

/**
 * PluginGeocode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class PluginGeocode extends BaseGeocode
{
  protected $foreignObject = null;

  public function getForeignObject()
  {
    if($this->foreignObject) return $this->foreignObject;
    
    $obj = Doctrine::getTable($this->getForeignTable())->find($this->getForeignId());
    if($obj)
    {
      $this->foreignObject = $obj;
      return $this->foreignObject;
    }
    return null;
  }

  public function getForeignTitle()
  {
    $obj = $this->getForeignObject();
    if($obj)
    {
      switch($this->getForeignTable())
      {
        case "Diary":
          return $obj->getTitle();
          break;
        case "DiaryComment":
          return $obj->getDiary()->getTitle()."へのコメント";
          break;
        case "CommunityTopic":
        case "CommunityEvent":
          return $obj->getName();
          break;
        case "CommunityTopicComment":
          return $obj->getCommunityTopic()->getName()."へのコメント";
          break;
        case "CommunityEventComment":
          return $obj->getCommunityEvent()->getName()."へのコメント";
          break;
      }
    }
    return;
  }
  
  public function getForeignUrl()
  {
    $obj = $this->getForeignObject();
    if($obj)
    {
      switch($this->getForeignTable())
      {
        case "Diary":
          return "diary/show?id=".$obj->getId();
          break;
        case "DiaryComment":
          return "diary/show?id=".$obj->getDiaryId();
          break;
        case "CommunityTopic":
          return "communityTopic/show?id=".$obj->getId();
          break;
        case "CommunityTopicComment":
          return "communityTopic/show?id=".$obj->getCommunityTopicId();
          break;
        case "CommunityEvent":
          return "communityEvent/show?id=".$obj->getId();
          break;
        case "CommunityEventComment":
          return "communityEvent/show?id=".$obj->getCommunityEventId();
          break;
      }
    }
    return;
  }
}