<?php

/**
 * PluginGeocode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opMapPlugin
 * @subpackage model
 * @author     Hiromi Hishida <info@77-web.com>
 * @version    0.9
 */
abstract class PluginGeocode extends BaseGeocode
{
  protected $foreignObject = null;

  public function getForeignObject()
  {
    if($this->foreignObject) return $this->foreignObject;
    
    $obj = Doctrine::getTable($this->getForeignTable())->find($this->getForeignId());
    if($obj)
    {
      $this->foreignObject = $obj;
      return $this->foreignObject;
    }
    return null;
  }

  public function getForeignTitle()
  {
    $obj = $this->getForeignObject();
    if($obj)
    {
      switch($this->getForeignTable())
      {
        case "Diary":
          return $obj->getTitle();
          break;
      }
    }
    return;
  }
  
  public function getForeignUrl()
  {
    $obj = $this->getForeignObject();
    if($obj)
    {
      switch($this->getForeignTable())
      {
        case "Diary":
          return "diary/show?id=".$obj->getId();
          break;
      }
    }
    return;
  }
  
  public function getGeocode()
  {
    return $this->getLat().','.$this->getLng();
  }
}