mapWinSuccess:
  has_layout: true
  layout: plain
  javascripts: ['http://maps.google.com/maps/api/js?sensor=false', '/opMapPlugin/js/googlemap_edit']

memberSuccess:
  javascripts: ['http://maps.google.com/maps/api/js?sensor=false', '/opMapPlugin/js/googlemap']

