options: 
  charset: utf8

#socialmap
Geocode:
  columns: 
    id: 
      type: integer(11)
      primary: true
      autoincrement: true
    lat: double
    lng: double
    member_id: integer(4)
    foreign_table: string(32)
    foreign_id: integer(11)
  relations:
    Member:
      onDelete: cascade
